
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Use the API key
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: echo $API_KEY
