
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set environment variable from secret
    run: echo "API_KEY=${{ secrets.MY_SECRET_VARIABLE }}" >> $GITHUB_ENV
